### PR TITLE
Add ability to customize navigation item from config file

### PR DESCRIPTION
**Pull request by aminetiyal**
This PR will add the ability to update navigation from the config file

```php
<?php
return [
    'navigation' => [
        'label' => 'Exceptions',
        'group' => 'System',
        'icon' => 'heroicon-o-chip',
    ]
];
```

By the default, it will have these values

### CODE REVIEW

**Comment by bezhanSalleh** [comment]
i know what you mean, but this way it won' t be translatable. 
now if you can update your PR to change these options via lang files then i will accept the PR.
that way even tabs, slug and labels would be translatable if someone wanted.

**Review by aminetiyal — COMMENTED** [review]
add trans helper

**Comment by aminetiyal** [comment]
> i know what you mean, but this way it won' t be translatable. now if you can update your PR to change these options via lang files then i will accept the PR. that way even tabs, slug and labels would be translatable if someone wanted.

@bezhanSalleh Here I added the trans helper to the nav label and group

**Comment by MarJose123** [comment]
is there a chance to approve this PR? as this plugin will mixed with the main component of your sidebar.

**Pull request merged**
