### PR TITLE
Add Custom Model Support & Fix Iterator Errors

### LINKED ISSUE #44: Allow for custom model
Hey,

Can you allow for custom model?

I'm using multiple database tenancy so need to modify the model to use the central connection :)

Thanks

### LINKED ISSUE #45: Error
I have the next issue https://flareapp.io/share/dPb918Nm 
I can't provide after what this was happened, because I missed the moment when it began to throw exception.

### PR DESCRIPTION
**Pull request by Fludem**
## Custom Models

Custom models are required in some scenarios such as having a multi tenant database where we want to enforce that the model uses the central database.

Changes made:

- Addded model option to configuration file
- Removed $model property and references in the Filament Resource and replaced with function getModel()
- Added Model method on FilamentExceptions.php that returns model class
- Added backwards compatibility to the model method
- Updated README.md to explain how to use this new feature

Closes #44 

## Fix Iterator Errors
In order to temporarily supress warnings & errors the \ReturnTypeWillChange attribute has been added to functions inside parser.php

Closes #45

### CODE REVIEW

**Comment by Fludem** [comment]
Hey @bezhanSalleh I updated workflow to test bench 8.0, I think it shouldn't cause problems but test workflow again

**Review by bezhanSalleh — CHANGES_REQUESTED** [review]
wasn't the issue. the issue was phpunit. could you merge it with the main though, it's fixed now.

**Comment by Fludem** [comment]
We missing anything

**Review by bezhanSalleh — APPROVED** [review]

**Comment by bezhanSalleh** [comment]
> We missing anything

nah, all seems. good. will do a release tonight. thanks.

**Comment by bezhanSalleh** [comment]
Thanks

**Comment by bezhanSalleh** [comment]
Thanks

**Pull request merged**
